'use client'
import {useEffect,useState} from 'react'
import BuyFlow from './BuyFlow'
import FoodFlow from './FoodFlow'
import TaskFlow from './TaskFlow'
import CompareFlow from './CompareFlow'
type Mode='home'|'food'|'buy'|'tasks'|'compare'|'random'|'history'
type Entry={id:string;type:string;title:string;result:string;date:string;mode:Mode}
const KEY='buddy-history'
// Every one of these throws for real: getItem in Safari private mode, JSON.parse on a
// partial write, setItem on a full quota, randomUUID outside a secure context. Any of
// them reaching React unhandled takes the whole app down to a blank error page.
const readHistory=():Entry[]=>{try{const raw=localStorage.getItem(KEY);const parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed:[]}catch{return []}}
const writeHistory=(items:Entry[])=>{try{localStorage.setItem(KEY,JSON.stringify(items))}catch{}}
const newId=()=>{try{return crypto.randomUUID()}catch{return Date.now().toString(36)+Math.random().toString(36).slice(2)}}
const modes=[['food','🍜','What Should I Eat?',"I'm hungry and somehow this became complicated."],['buy','🛍️','Should I Buy It?','Help me decide before I make another questionable purchase.'],['tasks','🔥','What Should I Do First?',"Everything feels urgent. Probably isn't."],['compare','⚖️','Help Me Choose','I have options. Too many options.']] as const
function Mascot({mood='happy',prop}:{mood?:'happy'|'think'|'sus'|'caught'|'sleep';prop?:string}){return <div className={'mascot '+mood} aria-label={`Buddy duck is ${mood}`}><b className="arm left"/><b className="arm right"/><i/><i/><span aria-hidden="true"/>{prop&&<em>{prop}</em>}</div>}
export default function DecisionBuddy(){const [mode,setMode]=useState<Mode>('home');const [history,setHistory]=useState<Entry[]>([]);useEffect(()=>{setHistory(readHistory());const sync=(e:StorageEvent)=>{if(e.key===KEY||e.key===null)setHistory(readHistory())};addEventListener('storage',sync);return()=>removeEventListener('storage',sync)},[]);const go=(m:Mode)=>{setMode(m);scrollTo(0,0)};const save=(type:string,title:string,result:string,m:Mode)=>{const next=[{id:newId(),type,title,result,date:new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'}),mode:m},...readHistory()].slice(0,20);setHistory(next);writeHistory(next)};return <><header><button className="brand" onClick={()=>go('home')}><Mascot/> <b>Decision Buddy</b></button><nav><button onClick={()=>go('home')}>Home</button><button onClick={()=>go('history')}>History <sup>{history.length||''}</sup></button></nav></header><main>{mode==='home'&&<Home go={go}/>} {mode==='random'&&<RandomMode save={save}/>} {mode==='buy'&&<BuyMode save={save}/>} {mode==='food'&&<FoodMode save={save}/>} {mode==='tasks'&&<TaskMode save={save}/>} {mode==='compare'&&<CompareMode save={save}/>} {mode==='history'&&<History items={history} go={go} remove={id=>{const n=readHistory().filter(x=>x.id!==id);setHistory(n);writeHistory(n)}}/>}</main><footer>Small decisions only. The big life stuff is still yours.</footer></>}
function Home({go}:{go:(m:Mode)=>void}){return <section className="home"><div className="doodle d1">✦</div><div className="doodle d2">♡</div><div className="doodle d3">?</div><div className="hero"><div className="heroBuddy"><Mascot/><span>hi!</span></div><p className="eyebrow">Your pocket-sized decision pal</p><h1>Can't decide?</h1><p>It’s okay. That’s literally why I’m here.</p></div><h2 className="sectiontitle">What’s today’s dilemma?</h2><div className="modegrid">{modes.map(([id,icon,title,sub],i)=><button className={`modecard card${i+1}`} key={id} onClick={()=>go(id)}><span className="cardicon" aria-hidden="true">{icon}</span><div><h2>{title}</h2><p>{sub}</p></div><b>↗</b></button>)}</div><button className="randomcard" onClick={()=>go('random')}><span aria-hidden="true">🎲</span><div><b>Just decide for me</b><small>My brain is off today.</small></div><b>→</b></button></section>}
function Shell({tag,title,sub,children}:{tag:string;title:string;sub:string;children:React.ReactNode}){return <section className="flow"><div className="questionhead"><Mascot mood={tag.toLowerCase().includes('verdict')?'sus':'happy'} prop={tag.toLowerCase().includes('buy')?'🛍️':undefined}/><div><p className="eyebrow">{tag}</p><h1>{title}</h1><p className="lede">{sub}</p></div></div>{children}</section>}
function OptionList({values,setValues,max=10}:{values:string[];setValues:(v:string[])=>void;max?:number}){return <div className="optionlist">{values.map((v,i)=><div className="optionrow" key={i}><span>{i+1}</span><input aria-label={`Option ${i+1}`} placeholder="Type an option…" value={v} onChange={e=>setValues(values.map((x,j)=>j===i?e.target.value:x))}/>{values.length>2&&<button aria-label="Remove option" onClick={()=>setValues(values.filter((_,j)=>j!==i))}>×</button>}</div>)}{values.length<max&&<button className="add" onClick={()=>setValues([...values,''])}>＋ Add another</button>}</div>}
function RandomMode({save}:{save:Function}){const [opts,setOpts]=useState(['Ramen','Hotpot','Subway']);const [winner,setWinner]=useState('');const [spinning,setSpinning]=useState(false);const [rejected,setRejected]=useState(false);const pick=(list=opts)=>{const clean=list.filter(Boolean);if(clean.length<2)return;setRejected(false);setSpinning(true);let n=0;const t=setInterval(()=>{setWinner(clean[Math.floor(Math.random()*clean.length)]);if(++n>10){clearInterval(t);const w=clean[Math.floor(Math.random()*clean.length)];setWinner(w);setSpinning(false);save('🎲','Quick pick',w,'random')}},70)};return <Shell tag="Just pick one" title="Okay, what are we choosing between?" sub="I’ll handle the deeply scientific part.">{!winner?<><OptionList values={opts} setValues={setOpts}/><button className="primary" onClick={()=>pick()}>🎲 Decide my fate</button></>:<div className={'result '+(spinning?'spinning':'')}><div className="sparkles">✦ · ✧</div><Mascot mood={spinning?'think':rejected?'caught':'happy'}/><p>{spinning?'Buddy is thinking…':rejected?'AHA!':'There. Problem solved.'}</p><h2>{rejected?'Crossing that one off.':winner.toUpperCase()+'!'}</h2>{!rejected&&<div className="actions"><button className="primary" onClick={()=>setWinner('')}>Fine 😌</button><button className="secondary" onClick={()=>{const n=opts.filter(x=>x!==winner);setOpts(n);setRejected(true);setTimeout(()=>{setWinner('');setTimeout(()=>pick(n),50)},700)}}>Absolutely not</button></div>}</div>}</Shell>}
function BuyMode({save}:{save:Function}){return <BuyFlow save={save as any}/>}
function FoodMode({save}:{save:Function}){return <FoodFlow save={save as any}/>}
function TaskMode({save}:{save:Function}){return <TaskFlow save={save as any}/>}
function CompareMode({save}:{save:Function}){return <CompareFlow save={save as any}/>}
function History({items,remove,go}:{items:Entry[];remove:(id:string)=>void;go:(m:Mode)=>void}){return <Shell tag="Saved on this device" title="Your recent decisions" sub="A tiny archive of things you no longer need to overthink.">{items.length?<div className="history">{items.map(x=><article key={x.id}><span>{x.type}</span><div><h2>{x.title}</h2><p>{x.result}</p><small>{x.date}</small></div><div><button onClick={()=>go(x.mode)}>Decide again</button><button onClick={()=>remove(x.id)}>Delete</button></div></article>)}</div>:<div className="empty"><Mascot mood="sleep"/><h2>Wow. Suspiciously decisive.</h2><p>Apparently you’ve been making decisions all by yourself. Impressive.</p><button className="primary" onClick={()=>go('home')}>Give Buddy something to do</button></div>}</Shell>}
